[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Note: You still need to add environment variables in Netlify Dashboard
# VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY