-- Add AI generation related fields to the 'stories' table
ALTER TABLE public.stories
ADD COLUMN IF NOT EXISTS generation_prompt TEXT NULL,
ADD COLUMN IF NOT EXISTS ai_generated_story BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS story_error_log TEXT NULL,
ADD COLUMN IF NOT EXISTS used_fallback_story BOOLEAN DEFAULT FALSE;

-- Add AI generation related fields to the 'characters' table
ALTER TABLE public.characters
ADD COLUMN IF NOT EXISTS generation_prompt TEXT NULL,
ADD COLUMN IF NOT EXISTS ai_generated_character BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS character_error_log TEXT NULL,
ADD COLUMN IF NOT EXISTS used_fallback_character BOOLEAN DEFAULT FALSE;

-- Comment to describe the migration
COMMENT ON COLUMN public.stories.generation_prompt IS 'The prompt used to generate the story content via AI.';
COMMENT ON COLUMN public.stories.ai_generated_story IS 'Flag indicating if the story content was generated by AI.';
COMMENT ON COLUMN public.stories.story_error_log IS 'Log of errors encountered during AI story generation.';
COMMENT ON COLUMN public.stories.used_fallback_story IS 'Flag indicating if fallback story content was used.';

COMMENT ON COLUMN public.characters.generation_prompt IS 'The prompt used to generate character attributes (e.g., background story) via AI.';
COMMENT ON COLUMN public.characters.ai_generated_character IS 'Flag indicating if character attributes were generated by AI.';
COMMENT ON COLUMN public.characters.character_error_log IS 'Log of errors encountered during AI character generation.';
COMMENT ON COLUMN public.characters.used_fallback_character IS 'Flag indicating if fallback character content was used.';
